UML_proj/UML_proj/Controllers/LearningParametersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UML_proj.Models;

namespace UML_proj.Controllers
{
    public class LearningParametersController : Controller
    {
        // GET: LearningParameters
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Update(Search_parameters updatedParameters)
        {
            ITProjektasDB db = new ITProjektasDB();
            if (updatedParameters != null)
            {
                db.Search_parameters.Add(updatedParameters);
                db.SaveChanges();
            }
            return View("LearningParametersForm", updatedParameters);
        }

        public ActionResult LearningParametersForm()
        {
            ITProjektasDB db = new ITProjektasDB();
            
            Search_parameters param = db.Search_parameters.SingleOrDefault(x => x.id_Search_parameters == 2);

            return View(param);
        }
    }
}

UML_proj/UML_proj/Views/LearningParameters/LearningParametersForm.cshtml
@model UML_proj.Models.Search_parameters

@{
    ViewBag.Title = "LearningParametersForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LearningParametersForm</h2>

@using (Html.BeginForm("Update", "LearningParameters", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Search_parameters</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Apsimokymo_greitis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apsimokymo_greitis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apsimokymo_greitis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Svoriai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Svoriai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Svoriai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Optimizavimo_metodas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Optimizavimo_metodas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Optimizavimo_metodas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Yra_pagrindinis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Yra_pagrindinis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Yra_pagrindinis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>