UML_proj/UML_proj/Models/Subscription.cs
namespace UML_proj.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Data.Entity.Spatial;
    using System.Linq;

    [Table("Subscription")]
    public partial class Subscription
    {
        ITProjektasDB db = new ITProjektasDB();
        public bool? receit_discord { get; set; }

        public bool? receit_email { get; set; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id_Subscription { get; set; }

        public int fk_Personid_Person { get; set; }

        public int fk_Newsletterid_Newsletter { get; set; }

        public virtual Newsletter Newsletter { get; set; }

        public virtual Person Person { get; set; }

        public List<Subscription> select_personal_subs()
        {
            var subscriptions = db.Subscriptions.Where(x => x.fk_Personid_Person==fk_Personid_Person).Include(s => s.Newsletter).Include(s => s.Person);
            return subscriptions.ToList();
        }

        public List<Subscription> select_subscribers()
        {
            var subscriptions = db.Subscriptions.Where(x => x.fk_Newsletterid_Newsletter==fk_Newsletterid_Newsletter).Include(s => s.Newsletter).Include(s => s.Person);
            return subscriptions.ToList();
        }
    }
}

UML_proj/UML_proj/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UML_proj.Models;

namespace UML_proj.Controllers
{
    public class SubscriptionController : Controller
    {
        Subscription sub_letters = new Subscription();
        ITProjektasDB db = new ITProjektasDB();

        // GET: ProfilePage
        public ActionResult open_profile_page() // open_profile_page()
        {
            return View("ProfilePage");
        }
 
        public ActionResult open_subscription_list() // open_subscription_list()
        {

            int id = Int32.Parse(Session["UserID"].ToString());
            return View("SubscriptionList");
            //return View("SubscriptionList", sub_letters.select(id,false).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscription sn = db.Subscriptions.Find(id);
            if (sn == null)
            {
                return HttpNotFound();
            }
            return View(sn);
        }



        public void delete_subscription()
        {

        }

        public void edit_receive_form()
        {

        }


        public void add_subscription()
        {

        }


        public void attempt_to_delete()
        {

        }


        public void get_subscriptions(int id)
        {

        }
    }
}

UML_proj/UML_proj/Controllers/SubscriptionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UML_proj.Models;

namespace UML_proj.Controllers
{
    public class SubscriptionsController : Controller
    {
        private ITProjektasDB db = new ITProjektasDB();
        private Subscription subs = new Subscription();

        // GET: Subscriptions
        public ActionResult Index()
        {
            var subscriptions = subs.select_personal_subs();
            return View(subscriptions);
        }
        public ActionResult open_subscription_list()
        {
            int id = Int32.Parse(Session["UserID"].ToString());
            //var subscriptions = subs.select_personal_subs();
            return View("Index",get_subscriptions(id));
        }

        public List<Subscription> get_subscriptions(int id)
        {
            if (id < 0 )
            {
                return new List<Subscription>();
            }
            subs.fk_Personid_Person = id;
            var test = subs.select_personal_subs();
            if(test.GetType() == typeof(List<Subscription>))
            {
                return test;
            }else
            {
                return new List<Subscription>();
            }
             
        }
        public ActionResult open_profile_page()
        {

            return View("ProfilePage"); // open
        }

        // GET: Subscriptions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscription subscription = db.Subscriptions.Find(id);
            if (subscription == null)
            {
                return HttpNotFound();
            }
            return View(subscription);
        }

        // GET: Subscriptions/Create
        public ActionResult Create()
        {
            ViewBag.fk_Newsletterid_Newsletter = new SelectList(db.Newsletters, "id_Newsletter", "newest_message");
            ViewBag.fk_Personid_Person = new SelectList(db.People, "id_Person", "name");
            return View();
        }

        // POST: Subscriptions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_Subscription,receit_discord,receit_email,fk_Personid_Person,fk_Newsletterid_Newsletter")] Subscription subscription)
        {
            if (ModelState.IsValid)
            {
                db.Subscriptions.Add(subscription);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.fk_Newsletterid_Newsletter = new SelectList(db.Newsletters, "id_Newsletter", "newest_message", subscription.fk_Newsletterid_Newsletter);
            ViewBag.fk_Personid_Person = new SelectList(db.People, "id_Person", "name", subscription.fk_Personid_Person);
            return View(subscription);
        }

        // GET: Subscriptions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscription subscription = db.Subscriptions.Find(id);
            if (subscription == null)
            {
                return HttpNotFound();
            }
            ViewBag.fk_Newsletterid_Newsletter = new SelectList(db.Newsletters, "id_Newsletter", "newest_message", subscription.fk_Newsletterid_Newsletter);
            ViewBag.fk_Personid_Person = new SelectList(db.People, "id_Person", "name", subscription.fk_Personid_Person);
            return View(subscription);
        }

        // POST: Subscriptions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_Subscription,receit_discord,receit_email,fk_Personid_Person,fk_Newsletterid_Newsletter")] Subscription subscription)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subscription).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_Newsletterid_Newsletter = new SelectList(db.Newsletters, "id_Newsletter", "newest_message", subscription.fk_Newsletterid_Newsletter);
            ViewBag.fk_Personid_Person = new SelectList(db.People, "id_Person", "name", subscription.fk_Personid_Person);
            return View(subscription);
        }

        // GET: Subscriptions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscription subscription = db.Subscriptions.Find(id);
            if (subscription == null)
            {
                return HttpNotFound();
            }
            return View(subscription);
        }

        // POST: Subscriptions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subscription subscription = db.Subscriptions.Find(id);
            db.Subscriptions.Remove(subscription);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UML_proj/UML_proj/Views/Subscriptions/Create.cshtml
@model UML_proj.Models.Subscription

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Subscription</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_Subscription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_Subscription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_Subscription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receit_discord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.receit_discord)
                    @Html.ValidationMessageFor(model => model.receit_discord, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receit_email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.receit_email)
                    @Html.ValidationMessageFor(model => model.receit_email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_Personid_Person, "fk_Personid_Person", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fk_Personid_Person", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_Personid_Person, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_Newsletterid_Newsletter, "fk_Newsletterid_Newsletter", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fk_Newsletterid_Newsletter", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_Newsletterid_Newsletter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UML_proj/UML_proj/Views/Subscriptions/Delete.cshtml
@model UML_proj.Models.Subscription

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Subscription</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Newsletter.newest_message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Newsletter.newest_message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receit_discord)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receit_discord)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receit_email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receit_email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UML_proj/UML_proj/Views/Subscriptions/Details.cshtml
@model UML_proj.Models.Subscription

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Subscription</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Newsletter.newest_message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Newsletter.newest_message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receit_discord)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receit_discord)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receit_email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receit_email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_Subscription }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UML_proj/UML_proj/Views/Subscriptions/Edit.cshtml
@model UML_proj.Models.Subscription

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Subscription</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_Subscription)

        <div class="form-group">
            @Html.LabelFor(model => model.receit_discord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.receit_discord)
                    @Html.ValidationMessageFor(model => model.receit_discord, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receit_email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.receit_email)
                    @Html.ValidationMessageFor(model => model.receit_email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_Personid_Person, "fk_Personid_Person", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fk_Personid_Person", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_Personid_Person, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fk_Newsletterid_Newsletter, "fk_Newsletterid_Newsletter", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fk_Newsletterid_Newsletter", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_Newsletterid_Newsletter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UML_proj/UML_proj/Views/Subscriptions/Index.cshtml
@model IEnumerable<UML_proj.Models.Subscription>

@{
    ViewBag.Title = "Index";
}

<h2>Subscription List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Newsletter.newest_message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Person.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.receit_discord)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.receit_email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Newsletter.newest_message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.receit_discord)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.receit_email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id_Subscription }) |
            @Html.ActionLink("Details", "Details", new { id=item.id_Subscription }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id_Subscription })
        </td>
    </tr>
}

</table>

UML_proj/UML_proj/Views/Subscriptions/ProfilePage.cshtml
@{
    ViewBag.Title = "ProfilePage";
}

<h2>Profile Page</h2>
<input type="button" value="Subscription List" onclick="location.href='@Url.Action("open_subscription_list", "Subscriptions")'"/>